canonicalization_type: group_equivariant
network_type: e2cnn # Options for canonization method 1) e2cnn 2) custom 3) equivariant_wrn 4) none
network_hyperparams:
  kernel_size: 5 # Kernel size for the canonization network
  out_channels: 64 # Number of output channels for the canonization network
  num_layers: 12 # Number of layers in the canonization network
  group_type: rotation # Type of group for the canonization network
  num_rotations: 4 # Number of rotations for the canonization network
beta: 1.0 # Beta parameter for the canonization network
input_crop_ratio: 0.8 # Ratio at which we crop the input to the canonicalization
resize_shape: 128 # Resize shape for the input
