canonicalization_type: steerable
network_type: e2cnn # Options for canonization method 1) e2cnn 2) custom 3) none
network_hyperparams:
  kernel_size: 7 # Kernel size for the canonization network
  out_channels: 16 # Number of output channels for the canonization network
  num_layers: 3 # Number of layers in the canonization network
  group_type: rotation # Type of group for the canonization network
input_crop_ratio: 0.8 # Ratio at which we crop the input to the canonicalization
