dataset:
  dataset_name: "rotated_mnist" # Name of the dataset to use
  data_path: "/home/mila/a/arnab.mondal/scratch/equiadapt/image/data" # Path to the dataset
  augment: 1 # Whether to use data augmentation (1) or not (0)

training:
  run_mode: "train" # Mode to run the model in, different run modes 1)dryrun 2)train 3)test 4)auto_tune
  seed: 0 # Seed for random number generation
  num_workers: 4 # Number of workers for data loading
  batch_size: 256 # Number of samples per batch
  num_epochs: 100 # Number of training epochs
  patience: 20 # Number of epochs with no improvement after which training will be stopped
  min_delta: 0.0 # Minimum change in the monitored quantity to qualify as an improvement
  lr: 0.001 # Learning rate

prediction:
  prediction_network_architecture: "resnet50" # Architecture of the prediction network
  use_pretrained: 0 # Whether to use pretrained weights (1) or not (0)
  freeze_pretrained_encoder: 0 # Whether to freeze the pretrained encoder (1) or not (0)

canonicalization:
  network_type: 'escnn' # Options o canonization method 1) escnn 
  network_hyperparams:
    kernel_size: 3 # Kernel size for the canonization network
    out_channels: 16 # Number of output channels for the canonization network
    num_layers: 3 # Number of layers in the canonization network
    num_freq: 1 # Number of frequencies for the canonization network
    group_type: "rotation" # Type of group for the canonization network
    num_channels: 20 # Number of channels for the canonization network

loss:
  prior_weight: 100.0 # Weight of the prior in the loss function
  prior_train_epochs: 20 # Number of epochs to train the prior

wandb:
  use_wandb: 1  # Whether to use Weights & Biases for logging (1) or not (0)
  wandb_project: "canonical_network" # Name of the Weights & Biases project
  wandb_entity: "symmetry_group" # Name of the Weights & Biases entity
  wandb_cache_dir: "/home/mila/a/arnab.mondal/scratch/wandb_artifacts" # Path to the Weights & Biases cache directory
  wandb_dir: "/home/mila/a/arnab.mondal/scratch/wandb" # Path to the Weights & Biases directory

checkpoint:
  checkpoint_path: "/home/mila/a/arnab.mondal/scratch/equiadapt/image/checkpoints" # Path to save checkpoints
  deterministic: false # Whether to set deterministic mode (true) or not (false)
  save_canonized_images: 0 # Whether to save canonized images (1) or not (0)