prediction_network_architecture: "sam" # Architecture of the prediction network
prediction_network_class: "vit_h" # Class of the prediction network
use_pretrained: 1 # Whether to use pretrained weights (1) or not (0)
freeze_encoder: 1 # Whether to freeze encoder (1) or not (0)
    
