checkpoint_path: "/home/mila/a/arnab.mondal/scratch/equiadapt/image/checkpoints" # Path to save checkpoints
checkpoint_name: "" # Model checkpoint name, should be left empty and dynamically allocated later
save_canonized_images: 0 # Whether to save canonized images (1) or not (0)